### ISSUE TITLE
child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]

### ISSUE THREAD

**Issue by Sprtcrnbry** [NextFire/apple-music-discord-rpc#25]
The RPC doesn't show up and the music-rpc.ts shows an error:
```
Client {
  ipc: DiscordIPC {},
  user: {
    id: "302644264876113920",
    username: "Paradise",
    discriminator: "0484",
    avatar: "06013634c97eae892225231844536591",
    avatar_decoration: null,
    bot: false,
    flags: 304
  },
  config: {
    cdn_host: "cdn.discordapp.com",
    api_endpoint: "//discord.com/api",
    environment: "production"
  },
  token: undefined,
  tokenExpires: undefined,
  application: undefined,
  options: { id: "773825528921849856" }
}
isOpen: true
state: playing
props: {
  class: "fileTrack",
  id: 446,
  index: 26,
  name: "Untitled 12 - 24:06:22 08.41",
  persistentID: "702F8B8A94AC3281",
  databaseID: 263,
  dateAdded: "2022-06-24T01:41:46.000Z",
  time: "3:36",
  duration: 216.88299560546875,
  artist: "",
  albumArtist: "",
  composer: "",
  album: "",
  genre: "",
  bitRate: 256,
  sampleRate: 44100,
  trackCount: 0,
  trackNumber: 0,
  discCount: 0,
  discNumber: 0,
  size: 7115081,
  volumeAdjustment: 0,
  year: 2022,
  comment: "",
  eq: "",
  kind: "AAC audio file",
  mediaKind: "song",
  modificationDate: "2022-06-24T01:41:38.000Z",
  enabled: true,
  start: 0,
  finish: 216.88299560546875,
  playedCount: 0,
  skippedCount: 1,
  skippedDate: "2022-07-01T07:15:29.000Z",
  compilation: false,
  rating: 0,
  bpm: 0,
  grouping: "",
  bookmarkable: false,
  bookmark: 0,
  shufflable: true,
  lyrics: "",
  category: "",
  description: "",
  episodeNumber: 0,
  unplayed: false,
  sortName: "",
  sortAlbum: "",
  sortArtist: "",
  sortComposer: "",
  sortAlbumArtist: "",
  loved: false,
  disliked: false,
  albumLoved: false,
  albumDisliked: false,
  cloudStatus: "unknown",
  work: "",
  movement: "",
  movementNumber: 0,
  movementCount: 0,
  location: {},
  playerPosition: 100.56300354003906
}
infos: { artwork: "appicon", url: null }
Error: (4000) child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
    at DiscordIPC.#read (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/conn.ts:180:11)
    at async https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/conn.ts:49:11
```

**Comment by NextFire** [comment]
The track is missing the artist name tag, I will push a fix to add a placeholder in these cases.

**Comment by Sprtcrnbry** [comment]
BTW, It also happens when a stream is played (File > Open Stream URL)
