### ISSUE TITLE
RangeError: IPC ID must be between 0-9

### ISSUE THREAD

**Issue by cluelessdev404** [NextFire/apple-music-discord-rpc#48]
The script can't seem to detect Discord. I'm on the latest version of the stable branch.

This is what I get when I manually run the script:
```
Client {
  ipc: DiscordIPC {},
  user: undefined,
  config: undefined,
  token: undefined,
  tokenExpires: undefined,
  application: undefined,
  options: { id: "..." } <-removed
}
```
Display current activity is enabled in Discord

macOS 13.1, Discord Stable 168826 (3146690)

**Comment by cluelessdev404** [comment]
I used these commands, in these order, to install:

```
brew install deno
brew tap nextfire/tap
brew install apple-music-discord-rpc
brew services restart apple-music-discord-rpc
```

None of them gave any errors during the install. `which deno` also points me to the path.

**Comment by NextFire** [comment]
Is there any other logging besides the `Client` one?

**Comment by cluelessdev404** [comment]
```
RangeError: IPC ID must be between 0-9
    at getIPCPath (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:14:31)
    at findIPC (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:30:16)
    at findIPC (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:41:12)
    at async Function.connect (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/conn.ts:40:18)
    at async Client.connect (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/client.ts:85:16)
    at async main (file:///usr/local/Cellar/apple-music-discord-rpc/0.5.0/bin/music-rpc.ts:70:5)
```

```
   NotFound: No such file or directory (os error 2)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:56:20)
    at async Function.loadCache (file:///usr/local/opt/apple-music-discord-rpc/bin/music-rpc.ts:27:20)
    at async start (file:///usr/local/opt/apple-music-discord-rpc/bin/music-rpc.ts:63:3) No valid cache.json found, generating a new cache...
BrokenPipe: Broken pipe (os error 32)
    at async write (deno:ext/net/01_net.js:27:12)
    at async DiscordIPC.send (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/conn.ts:81:5)
```

**Comment by NextFire** [comment]
Can you try this https://github.com/NextFire/apple-music-discord-rpc/issues/43#issuecomment-1321221961 and report me what you see in the Discord console?

**Comment by cluelessdev404** [comment]
Sorry for the late response, it just started working again. I changed my status from online to invisible then online again, then restarted discord and it worked. Thanks again.
