### ISSUE TITLE
Can't get the app to work anymore

### ISSUE THREAD

**Issue by igoroliveiragc** [NextFire/apple-music-discord-rpc#52]
Sorry I am not a pro-user, just a newbie. The app wont work for me anymore even after updating with _brew upgrade_

This is what the terminal is printing:

```
Client {
  ipc: DiscordIPC {},
  user: undefined,
  config: undefined,
  token: undefined,
  tokenExpires: undefined,
  application: undefined,
  options: { id: "773825528921849856" }
}
isOpen: true
state: playing
Error: Can't get object.
    at handleError (https://raw.githubusercontent.com/NextFire/jxa/64b6de1748ea063c01271edbe9846e37a584e1ab/run/mod.ts:180:9)
    at runInOsascript (https://raw.githubusercontent.com/NextFire/jxa/64b6de1748ea063c01271edbe9846e37a584e1ab/run/mod.ts:152:21)
    at async setActivity (file:///opt/homebrew/bin/music-rpc.ts:189:21)
    at async file:///opt/homebrew/bin/music-rpc.ts:74:9
```

**Comment by NextFire** [comment]
Did you try a reboot?

**Comment by igoroliveiragc** [comment]
> Did you try a reboot?

thank you, a reboot did it for me
